# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wohaseverapp', '0002_auto_20181216_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_title',
        ),
    ]
