# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wohaseverapp', '0003_auto_20181219_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='category_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='category_img/'),
            preserve_default=False,
        ),
    ]
